# This is a config for E2B sandbox template.
# You can use template ID (glbo1benr4poiaxr8df9) or template name (vibe-test-rishav2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-test-rishav2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-test-rishav2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-test-rishav2')

team_id = "307378f5-2096-43e7-82ba-ab9593754f15"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-test-rishav2"
template_id = "glbo1benr4poiaxr8df9"
